name: "AI Code Review"
description: "Analyze pull request code and provide AI-based review comments"
author: "laxman0702"

runs:
  using: "node20"   # safer than node24 for now
  main: "dist/index.js"

branding:
  icon: "check-circle"
  color: "blue"
